# POST http://localhost:5000/user/login
# Content-Type: "application/json",

# {
#     "email":"test@mail.com",
#     "password":"test"
# }

# 
POST https://client-bot-server.herokuapp.com/user/bot/webhook HTTP/1.1
content-type: application/json

{

        "sender":"1",
    "message":"/greetings.bye"

}
# https://client-bot-server.herokuapp.com
# POST http://localhost:5000/api/v1/sales/consolidated
# Content-Type: "application/json",
# Authorization: Bearer eccbc87e4b5ce2fe28308fd9f2a7baf3c20ad4d76fe97759aa27a0c99bff6710


